In [1]:
import numpy as np

In [2]:
simple_list = np.arange(15)
simple_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
grades = np.arange(1,13)
grades

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
grade_groups = grades.reshape(3,4)

In [5]:
grade_groups

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
grade_groups[1]

array([5, 6, 7, 8])

In [9]:
grade_groups[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
grade_groups[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [11]:
grade_groups

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
grade_groups[:2:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])